### ISSUE TITLE
Require module-core

### ISSUE THREAD

**Issue by kszymukowicz** [mageplaza/magento-2-italian-language-pack#1]
hi

what is the reason that you require "mageplaza/module-core": "^1.3.1|dev-master"?

I'd like to use italian-language-pack but I do not suppose I need mageplaza/module-core at all :)

**Comment by zebeel** [comment]
All module/extension develop by Mageplaza must require the mageplaza/module-core. It is the policy of Mageplaza.

**Comment by kszymukowicz** [comment]
I was supposing its marketing but its very poor marketing then. 
You loose a lot. I do not trust your extensions if you use it for marketing purpose.
